rails_velocity/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :components
  resources :bikes
  resources :users

  mount API::Base, at: "/"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails_velocity/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_velocity/app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :components, dependent: :destroy
end

rails_velocity/app/models/component.rb
class Component < ApplicationRecord
  belongs_to :bike
end

rails_velocity/app/models/user.rb
class User < ApplicationRecord
  has_many :bikes, dependent: :destroy
end

rails_velocity/app/controllers/api/base.rb
module API
  class Base < Grape::API
    mount API::V1::Base
  end
end

rails_velocity/app/controllers/api/v1/base.rb
module API
  module V1
    class Base < Grape::API
      mount API::V1::Users
      # mount API::V1::Bikes
      # mount API::V1::Components
    end
  end
end

rails_velocity/app/controllers/api/v1/defaults.rb
module API
  module V1
    module Defaults
      extend ActiveSupport::Concern

      included do
        prefix "api"
        version "v1", using: :path
        default_format :json
        format :json
        formatter :json,
             Grape::Formatter::ActiveModelSerializers

        helpers do
          def permitted_params
            @permitted_params ||= declared(params,
               include_missing: false)
          end

          def logger
            Rails.logger
          end
        end

        rescue_from ActiveRecord::RecordNotFound do |e|
          error_response(message: e.message, status: 404)
        end

        rescue_from ActiveRecord::RecordInvalid do |e|
          error_response(message: e.message, status: 422)
        end
      end
    end
  end
end

rails_velocity/app/controllers/api/v1/users.rb
module API
  module V1
    class Users < Grape::API
      include API::V1::Defaults
      resource :users do
        desc 'Returns all users'
        get "" do
          User.all
        end

        desc 'Returns a specific user'
        get "/:user_id" do
          # User.where(id: params[:user_id])
          Bike.where(user_id: params[:user_id])
        end
      end
    end
  end
end

rails_velocity/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails_velocity/app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = Bike.all
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
  end

  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit
  end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render :show, status: :created, location: @bike }
      else
        format.html { render :new }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bikes/1
  # PATCH/PUT /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { render :show, status: :ok, location: @bike }
      else
        format.html { render :edit }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike.destroy
    respond_to do |format|
      format.html { redirect_to bikes_url, notice: 'Bike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike
      @bike = Bike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bike_params
      params.require(:bike).permit(:bike_name, :distance, :user_id)
    end
end

rails_velocity/app/controllers/components_controller.rb
class ComponentsController < ApplicationController
  before_action :set_component, only: [:show, :edit, :update, :destroy]

  # GET /components
  # GET /components.json
  def index
    @components = Component.all
  end

  # GET /components/1
  # GET /components/1.json
  def show
  end

  # GET /components/new
  def new
    @component = Component.new
  end

  # GET /components/1/edit
  def edit
  end

  # POST /components
  # POST /components.json
  def create
    @component = Component.new(component_params)

    respond_to do |format|
      if @component.save
        format.html { redirect_to @component, notice: 'Component was successfully created.' }
        format.json { render :show, status: :created, location: @component }
      else
        format.html { render :new }
        format.json { render json: @component.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /components/1
  # PATCH/PUT /components/1.json
  def update
    respond_to do |format|
      if @component.update(component_params)
        format.html { redirect_to @component, notice: 'Component was successfully updated.' }
        format.json { render :show, status: :ok, location: @component }
      else
        format.html { render :edit }
        format.json { render json: @component.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /components/1
  # DELETE /components/1.json
  def destroy
    @component.destroy
    respond_to do |format|
      format.html { redirect_to components_url, notice: 'Component was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_component
      @component = Component.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def component_params
      params.require(:component).permit(:comp_name, :distance_done, :max_distance, :bike_id)
    end
end

rails_velocity/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

rails_velocity/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :strava_id, :access_token, :access_token_expiry, :refresh_token)
    end
end

rails_velocity/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_velocity/app/helpers/bikes_helper.rb
module BikesHelper
end

rails_velocity/app/helpers/components_helper.rb
module ComponentsHelper
end

rails_velocity/app/helpers/home_helper.rb
module HomeHelper
end

rails_velocity/app/helpers/users_helper.rb
module UsersHelper
end

rails_velocity/app/views/bikes/_form.html.erb
<%= form_with(model: bike, local: true) do |form| %>
  <% if bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
        <% bike.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bike_name %>
    <%= form.text_field :bike_name %>
  </div>

  <div class="field">
    <%= form.label :distance %>
    <%= form.number_field :distance %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails_velocity/app/views/bikes/edit.html.erb
<h1>Editing Bike</h1>

<%= render 'form', bike: @bike %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>

rails_velocity/app/views/bikes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bikes</h1>

<table>
  <thead>
    <tr>
      <th>Bike name</th>
      <th>Distance</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bikes.each do |bike| %>
      <tr>
        <td><%= bike.bike_name %></td>
        <td><%= bike.distance %></td>
        <td><%= bike.user_id %></td>
        <td><%= link_to 'Show', bike %></td>
        <td><%= link_to 'Edit', edit_bike_path(bike) %></td>
        <td><%= link_to 'Destroy', bike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bike', new_bike_path %>

rails_velocity/app/views/bikes/new.html.erb
<h1>New Bike</h1>

<%= render 'form', bike: @bike %>

<%= link_to 'Back', bikes_path %>

rails_velocity/app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bike name:</strong>
  <%= @bike.bike_name %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @bike.distance %>
</p>

<p>
  <strong>User:</strong>
  <%= @bike.user_id %>
</p>

<%= link_to 'Edit', edit_bike_path(@bike) %> |
<%= link_to 'Back', bikes_path %>

rails_velocity/app/views/home/index.html.erb
<%= react_component 'GreetUser', name: 'Gabriel' %>

rails_velocity/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsVelocity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_velocity/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :strava_id %>
    <%= form.number_field :strava_id %>
  </div>

  <div class="field">
    <%= form.label :access_token %>
    <%= form.text_field :access_token %>
  </div>

  <div class="field">
    <%= form.label :access_token_expiry %>
    <%= form.text_field :access_token_expiry %>
  </div>

  <div class="field">
    <%= form.label :refresh_token %>
    <%= form.text_field :refresh_token %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails_velocity/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

rails_velocity/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Strava</th>
      <th>Access token</th>
      <th>Access token expiry</th>
      <th>Refresh token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.strava_id %></td>
        <td><%= user.access_token %></td>
        <td><%= user.access_token_expiry %></td>
        <td><%= user.refresh_token %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

rails_velocity/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

rails_velocity/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Strava:</strong>
  <%= @user.strava_id %>
</p>

<p>
  <strong>Access token:</strong>
  <%= @user.access_token %>
</p>

<p>
  <strong>Access token expiry:</strong>
  <%= @user.access_token_expiry %>
</p>

<p>
  <strong>Refresh token:</strong>
  <%= @user.refresh_token %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>